repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.2
  hooks:
  - id: gitleaks
- repo: https://github.com/tofuutils/pre-commit-opentofu
  rev: v1.0.2
  hooks:
  - id: tofu_fmt
  - id: tofu_docs
    args:
    - '--args=--lockfile=false'
    - '--args=--output-file=README.md'
  - id: opentofu_tflint
    args:
    - '--args=--recursive'
  - id: tofu_validate
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
